#!/bin/bash
# Usage: curl https://raw.githubusercontent.com/nuada/rna-course/master/apply | bash -s

# Setup puppetlabs APT repos
source /etc/lsb-release
rm -rf /etc/apt/sources.list.d/puppetlabs.list.*
cat << EOF > /etc/apt/sources.list.d/puppetlabs.list
deb http://apt.puppetlabs.com ${DISTRIB_CODENAME} main
deb-src http://apt.puppetlabs.com ${DISTRIB_CODENAME} main
deb http://apt.puppetlabs.com ${DISTRIB_CODENAME} dependencies
deb-src http://apt.puppetlabs.com ${DISTRIB_CODENAME} dependencies
EOF

# Install/update puppet
apt-get update
if which puppet; then
	puppet apply -e "package { 'puppet': ensure => latest; 'git': ensure => present; }"
else
	apt-get install -y puppet git
fi

# Install apt puppet module
if [[ ! $(puppet module list | grep puppetlabs-apt) ]]; then
	puppet module install puppetlabs/apt
fi

# If not running from repo clone it
if [[ $0 == 'bash' ]]; then
	git clone https://github.com/nuada/rna-course
	cd rna-course
fi

puppet apply --verbose $* manifests
